apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projeto-app
  template:
    metadata:
      labels:
        app: projeto-app
    spec:
      containers:
      - name: projeto-app
        image: henrique545/projeto-app:54689b621477064f3916fe1b0b38c8eec1fb4dff
        ports:
        - containerPort: 8000