apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projeto-app
  template:
    metadata:
      labels:
        app: projeto-app
    spec:
      containers:
      - name: projeto-app
        image: henrique545/projeto-app:88e72f1b9ac02c0c4153420de325e6537b11bf56
        ports:
        - containerPort: 8000